# kustomize build envoy --enable-helm | kubectl apply -f -
resources:
- namespace.yaml
- quickstart.yaml

helmCharts:
- name: gateway-helm
  namespace: envoy-gateway-system
  repo: oci://docker.io/envoyproxy
  version: 1.7.1